### PR TITLE
Tight integration latest

### PR DESCRIPTION
**Pull request by yuewko**

### CODE REVIEW

**Comment by yuewko** [comment]
@fturib, @rajansandeep, @chrisohaver: here's PR for CoreDNS-Themis tight integration.

Please make sure you do a squash when it's merged.

**Comment by fturib** [comment]
I am ok with that PR.
Although this code will be soon refactor. (due to change in Design - see PR #2).

But we need to go ahead. What is the best option ?
1- merge this into the repo + add in the README "Work in progress" ?
2- or continue to work on Ko's repo ?

**Comment by yuewko** [comment]
Option 3 ;-)

Merge this PR into a branch, instead of master. 

WDYT?

**Comment by fturib** [comment]
yes. good idea. I did not thought of it.
Can we merge in a branch "integration-wip" ?

**Comment by yuewko** [comment]
@fturib, sounds good! However, I don't have permission to create branches.

Could you please create the branch? After which, I'll update the PR to that as the base branch.

Thanks!!

**Comment by chrisohaver** [comment]
@yuewko, is this still active? Or can we close it?

**Comment by yuewko** [comment]
@chrisohaver , as far as I am concerned, it is not active. Unless there's still need for this, it can be closed.

**Comment by chrisohaver** [comment]
This PR is superseded by #12.

**Pull request closed without merging**
